### ISSUE TITLE
As a user, I want to view my current progress of tasks within each plan

### ISSUE THREAD

**Issue by jiayushe** [AY1920S1-CS2103T-W11-1/main#104]
... so I can keep track of my progress and avoid missing the target deadline.

**Comment by tiuweehan** [comment]
Are you planning to do the UI for this? If not I'll work on it

**Comment by jiayushe** [comment]
> Are you planning to do the UI for this? If not I'll work on it

Yea this issue is all about UI lol.

**Comment by tiuweehan** [comment]
Ok sure. FYI I've made a skeleton UI for plans in my PR, but you can add on your features to it
