### ISSUE TITLE
Content in the details panel should not be editable

### ISSUE THREAD

**Issue by le0tan** [AY1920S1-CS2103T-W11-1/main#152]
![image](https://user-images.githubusercontent.com/28982486/67916799-e2018d80-fbd1-11e9-9f6d-cdf2b3f42e78.png)

**Comment by tiuweehan** [comment]
Actually I might just make it editable and saveable

**Comment by le0tan** [comment]
> Actually I might just make it editable and saveable

If it's not editable/savable in v1.3 probably at least we should temporarily make it not editable just to not confuse the testers?
