### ISSUE TITLE
Bug: Allow multiple methods and sorting orders

### ISSUE THREAD

**Issue by ZhangHuafan** [AY1920S1-CS2103T-W11-1/main#225]
You should either clarify in UG or disallow entering multiple parameters.
Reproduce: sortprob m/author ord/descend m/difficulty ord/ascend
<img width="657" alt="Screen Shot 2019-11-07 at 6 49 03 PM" src="https://user-images.githubusercontent.com/46707623/68382825-769a5b80-018f-11ea-9aa4-85d21629254a.png">

**Comment by le0tan** [comment]
This is a parser problem with AB3: AB3's parser will only accept the last parameter value if there are duplicate valid parameters. We should update our user guide to warn the user against providing such inputs. @Seris370 @tiuweehan @jiayushe @LuWenQ 

Thanks for your report @ZhangHuafan !
