### ISSUE TITLE
Suggestion: add more restrictions for parsing numbers 

### ISSUE THREAD

**Issue by ZhangHuafan** [AY1920S1-CS2103T-W11-1/main#226]
Such command is allowed: findprob diff/1.-2
<img width="651" alt="Screen Shot 2019-11-07 at 6 59 05 PM" src="https://user-images.githubusercontent.com/46707623/68383735-29b78480-0191-11ea-9853-e5a6ff4d0fd2.png">

**Comment by le0tan** [comment]
This parsing rule is specified by Java's standard library: `Double.parseDouble`. So probably we won't fix this for now.

Thanks for the report!
