### ISSUE TITLE
Bug: incorrect example given for help

### ISSUE THREAD

**Issue by ZhangHuafan** [AY1920S1-CS2103T-W11-1/main#228]
hlep find
<img width="518" alt="Screen Shot 2019-11-07 at 7 26 57 PM" src="https://user-images.githubusercontent.com/46707623/68385414-a730c400-0194-11ea-824d-314e44c2564b.png">
<img width="571" alt="Screen Shot 2019-11-07 at 7 26 50 PM" src="https://user-images.githubusercontent.com/46707623/68385416-a7c95a80-0194-11ea-99ed-7b8ad2648dd3.png">

**Comment by le0tan** [comment]
This is due to https://github.com/AY1920S1-CS2103T-W11-1/main/pull/210
