### ISSUE TITLE
Bug: problem name cannot match punctuations

### ISSUE THREAD

**Issue by ZhangHuafan** [AY1920S1-CS2103T-W11-1/main#229]
Enter the following command the problem will not be shown
<img width="332" alt="Screen Shot 2019-11-07 at 7 14 34 PM" src="https://user-images.githubusercontent.com/46707623/68384819-6a180200-0193-11ea-8acb-988b7b4e4d53.png">

**Comment by le0tan** [comment]
It's described here in the UG of `findprob`:

![image](https://user-images.githubusercontent.com/28982486/68390005-4eb2f400-019f-11ea-825d-fc450c0d4213.png)

So here `Bipartite?` is considered as a word, and simply matching `bipartite` or `?` won't work as as match "word" by "word".

I will update the DG to inform user to avoid writing "word?" and "word." and "word!" in the problem name. Thanks for your report!
